### ISSUE TITLE
feat: Make sidebar dropdowns functional [⭐4xp]

### ISSUE THREAD

**Issue by IndieCoderMM** [IndieCoderMM/convoz-chat#19]
The channel dropdowns on the sidebar are purely visual currently. The goal is to make these dropdowns interactive and functional, similar to how it works in Discord.

## 🎯Todos
- [ ] Modify [features/Chat/ChannelList.tsx](https://github.com/IndieCoderMM/convoz-chat/blob/dev/src/features/Chat/ChannelList.tsx) by creating trigger and dropdown items
- [ ] Implement functionality to open/close dropdown on clicks
- [ ] Add smooth transitions
- [ ] Use Tailwind CSS
- [ ] Make the dropdown accessible

![image](https://github.com/IndieCoderMM/convoz-chat/assets/72640048/d3eb743d-a26c-4feb-aa2f-65dff28f900e)
